#!/bin/sh

#
# Start the demo
#

case "$1" in
  start)
	printf "Starting demo: "
	/usr/lib/qt/examples/gui/analogclock/analogclock &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping demo: "
	/usr/bin/killall analogclock
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

