#!/bin/sh

#
# Start the demo
#

case "$1" in
  start)
	printf "Starting demo: "
	kmstest -D /dev/dri/card0 -M sun4i-drm
	/usr/bin/screen_test &
	cat /sys/class/backlight/backlight/max_brightness > /sys/class/backlight/backlight/brightness
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping demo: "
	/usr/bin/killall screen_test
	echo 0 > /sys/class/backlight/backlight/brightness
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

