#!/bin/sh
#
# Start the udhcpd
#

case "$1" in
  start)
	printf "Starting udhcpd: "
	/usr/sbin/udhcpd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping udhcpd: "
	/usr/bin/killall udhcpd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

