#!/bin/sh

#
# Turn on the backlight
#

case "$1" in
  start)
	cat /sys/class/backlight/backlight/max_brightness > /sys/class/backlight/backlight/brightness
	;;
  stop)
	echo 0 > /sys/class/backlight/backlight/brightness
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

