#!/bin/sh

mount -t proc none /proc

# process kernel and passed in command-line parameters
set -- $(cat /proc/cmdline) "$@"
for arg in "$@"; do
  case "$arg" in
    overlay.src=*)
      mountsrc="${arg#overlay.src=}"
      ;;
    overlay.type=*)
      mounttype="-t ${arg#overlay.type=}"
      ;;
  esac
done


# mount the new rootfs
mount $mounttype $mountsrc /overlay

mkdir -p /overlay/rootfs /overlay/rw /overlay/work
mount -t overlay overlay /overlay/rootfs -o lowerdir=/,upperdir=/overlay/rw,workdir=/overlay/work
mkdir -p /overlay/rootfs/oldroot
cd /overlay/rootfs

# mount /dev and /sys for chroot environment
# /dev/pts, /dev/shm, /proc, /tmp and /run will be mounted by inittab from fstab
mount -t sysfs sysfs /sys
mount --rbind /sys /overlay/rootfs/sys/
mount --rbind /dev /overlay/rootfs/dev/

# exec chroot /chroot /sbin/init
pivot_root . oldroot
exec /sbin/init
